### ISSUE TITLE
wave form display issue

### ISSUE THREAD

**Issue by sunzhongmeng** [RR-Inyo/Volquo_ESP32#1]
hi,I have made a same prototype based on your article,but the Power Supply is AC220V,so I made some necessary changes:

1. TURN_RATIO = 220/7.557  (the actual voltage of the transformer is 7.557V );
2. V_rms_alert_U = 235.0;//105.0  (220V+7%)
3. V_rms_alert_L = 198.0;//96.0   (220V-10%)
4. hMeter hmVolt(108, 85, 200.0, 240.0);
5. tdPlot tdWaveform(104, 125, -240.0, 240.0);
![wave](https://user-images.githubusercontent.com/4470014/205856595-5bcd4c2e-04b2-44f8-a75d-824468ed2e0b.jpg)

But the waveform is not displayed correctly.do you have any suggestions?

**Comment by RR-Inyo** [comment]
Thank you for the comment. I think the part below is erroneous.

`tdPlot tdWaveform(104, 125, **-240.0, 240.0**);`

It is a basic of electrical engineering.

If the AC voltage in your country is 220 V, this "220 V" means "effective value" or "root mean square (RMS)". The peak value of the sinusoidal wave having 220 V of RMS value is 1.4142 (square root of 2) times higher than the RMS value. Thus, the peak value of your AC voltage waveform is 220 x 1.4142 = 311.1 V.

I think you need to set "400" or "450" instead of "240" to define the tdPlot object.

Sincerely.

**Comment by sunzhongmeng** [comment]
> 

Thank you very much for your reply.I'm terribly sorry.I made a terrible mistake.This program is very complicated for me i also need to read your program carefully.
